notdienste/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html',
        'redirect_field_name': 'redirect'},
        name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'},
        name='logout'),
    url(r'^p/', include('payments.urls', namespace='payments')),
    url(r'', include('services.urls', namespace='services')),
)

payments/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from payments import views

urlpatterns = patterns('payments.views',
    url(r'^l/$', 'list', name='list'),
    url(r'^b/(\d)$', 'bill', name='bill'),
    url(r'^p/$', 'payment', name='payment'),
    url(r'^co/$', 'checkout', name='checkout'),
    url(r'^s/$', 'subscription', name='subscription'),
)

services/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from services import views

urlpatterns = patterns('services.views',
    url(r'^$', 'index', name='index'),
    url(r'^e/(\d)/$', 'search', name='search'),
    url(r'^c/(\d)/$', 'category', name='category'),
    url(r'^s/(\d)/$', 'service', name='service'),
    url(r'^m/$', 'manage', name='manage'),
    url(r'^m/v/$', 'verification', name='verification'),
    url(r'^m/pd/$', 'personal_data', name='personal_data'),
)

payments/models.py
from django.db import models

from services.models import User

class Payment(models.Model):
    yearly = models.BooleanField(default=False)
    amount = models.IntegerField()
    date = models.DateField(auto_now=True)
    user = models.ForeignKey(User)

    def __str__(self):
        return 'Payment {}: {}€ on {} by {}'.format(self.pk, self.amount,
            self.date, self.user)

    def pretty(self):
        return 'Zahlung über {}€ am {}'.format(self.amount, self.date)

services/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class Location(models.Model):
    plz = models.IntegerField()
    lon = models.FloatField()
    lat = models.FloatField()
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return str(self.plz) + ' - ' + self.name

    def __str__(self):
        return str(self.plz) + ' - ' + self.name

class Service(models.Model):
    owner = models.ForeignKey('User')
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=50)
    desc = models.TextField(blank=True)
    tel = models.CharField(max_length=15)
    website = models.URLField(blank=True)
    plz = models.IntegerField()
    lon = models.FloatField()
    lat = models.FloatField()

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    def num_ratings(self):
        return len(Rating.objects.filter(of=self))

    def average_rating(self):
        try:
            l = []
            for r in Rating.objects.filter(of=self):
                l += [r.stars]
            return round(sum(l)/float(len(l)), 2)
        except:
            return 0

class Rating(models.Model):
    by = models.ForeignKey(settings.AUTH_USER_MODEL)
    of = models.ForeignKey(Service)
    at = models.DateTimeField(auto_now=True)
    stars = models.IntegerField()
    text = models.TextField(blank=True)

    def __unicode__(self):
        return self.by.username + '  - ' + self.of.name

    def __str__(self):
        return self.by.username + '  - ' + self.of.name

class User(AbstractUser):
    provider = models.BooleanField(default=False)
    favourites = models.ManyToManyField(Service, related_name='favourites')
    verified = models.BooleanField(default=False)
    subscribed = models.BooleanField(default=False) # Yearly subscription
    paid = models.IntegerField(default=0)

    def num_services(self):
        return len(Service.objects.filter(owner=self))

services/forms.py
from django import forms

class PersonalDataForm(forms.Form):
    FirstName = forms.CharField(label='Vorname')
    LastName = forms.CharField(label='Nachname')

class AddressForm(forms.Form):
    Name = forms.CharField(label='Name')
    Street = forms.CharField(label='Straße')
    City = forms.CharField(label='PLZ / Stadt')

payments/views.py
from django.shortcuts import render, redirect, get_object_or_404

from notdienste.settings import PAYMENT_BACKEND, MONTHLY_PRIZE
from payments.models import Payment
from payments.util import create_payment
from services.models import User

def list(request):
    if not request.user.is_authenticated():
        return redirect('/')

    payments = Payment.objects.filter(user=request.user).order_by('-date')

    context = {
        'payments': payments,
    }

    return render(request, 'payments/list.html', context)

def bill(request, pid):
    if not request.user.is_authenticated():
        return redirect('/')

    payment = get_object_or_404(Payment, pk=pid)

    # TODO Generate a bill to print out.

    return render(request, 'services/bill.html')

def payment(request):
    if not request.user.is_authenticated():
        return redirect('/')

    context = {
        'token': PAYMENT_BACKEND.get_client_token(request.user),
    }

    return render(request, 'payments/payment.html', context)

def checkout(request):
    if request.method != 'POST' or not request.user.is_authenticated():
        return redirect('/')

    if create_payment(request.user, request.POST.get('payment_method_nonce'),
        MONTHLY_PRIZE):
        p = Payment()
        p.yearly = False # This is a monthly payment.
        p.user = request.user
        p.amount = MONTHLY_PRIZE
        p.save()

        request.user.paid += 30
        request.user.save()

        return render(request, 'payments/payment_complete.html')
    else:
        return render(request, 'payments/payment_failed.html')

def subscription(request):
    if not request.user.is_authenticated():
        return redirect('/')

    if request.method == 'POST':
        if request.POST.get('sub')  and not request.user.subscribed:
            request.user.subscribed = True
            request.user.save()
            # TODO generate a bill and send it
            # TODO indicate success
        elif request.POST.get('unsub') and request.user.subscribed:
            request.user.subscribed = False
            request.user.save()
            # TODO indicate success

    return render(request, 'payments/subscription.html')

services/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.hashers import check_password, make_password

from notdienste.settings import SUPPORT_EMAIL
from services.forms import PersonalDataForm, AddressForm
from services.models import *
from services.util import get_distances
from services.paginator import paginate
from services.text import UNKNOWN_PLZ
# from .forms import CaptchaForm

def index(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }

    return render(request, 'index.html', context)

def search(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {
        'category': category
    }

    return render(request, 'services/search.html', context)

def category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)

    try:
        plz = Location.objects.get(plz=request.GET['plz'])

    except:
        context = {
            'error': UNKNOWN_PLZ.format(SUPPORT_EMAIL)
        }
        return render(request, 'error.html', context)

    services = Service.objects.filter(category=category)

    distances = get_distances(plz, services)

    # Put them in a list, so they are sortable, and sort them by
    # distance.
    slist = []
    for service in distances:
        slist += [(distances[service], service)]
    slist.sort()
    servicelist = paginate(slist, 10, request.GET.get('p'))

    context = {
        'plz': plz,
        'category': category,
        'distances': distances,
        'servicelist': servicelist
    }

    return render(request, 'services/category.html', context)

def service(request, service_id):
    service = get_object_or_404(Service, pk=service_id)
    context = {}
    # Contact data was requested, check the captcha.
    # context['contact'] = 0
    # if request.method == 'POST':
    #     form = CaptchaForm(request.POST)
    #     if form.is_valid():
    #         context['contact'] = 1
    # else:
    #     form = CaptchaForm()

    if request.user.is_authenticated():
        try:
            r = Rating.objects.get(by=request.user, of=service)
            context['rating'] = r
        except: # There is no past rating of this user for this service.
            pass
        if 'r' in request.GET:
            rs = int(request.GET['r'])
            try:
                r.stars = rs
            except:
                r = Rating(by=request.user, of=service, stars=rs)
            r.text = request.GET['rt']
            if 6 > rs > 0:
                r.save()
            context['rating'] = r

    ratings = paginate(Rating.objects.filter(of=service).order_by('-at'), 5,
                       request.GET.get('p'))

    context['service'] = service
    context['ratings'] = ratings
    # context['form'] = form

    return render(request, 'services/service.html', context)

def manage(request):
    if not request.user.is_authenticated():
        return redirect('/')

    context = {
        'listings': Service.objects.filter(owner=request.user)
    }

    return render(request, 'services/manage.html', context)

def personal_data(request):
    if not request.user.is_authenticated():
        return redirect('/')

    # TODO Checking POST for submitted data, saving this into models
    # that have yet to be created.

    context = {
        'pdform': PersonalDataForm,
        'paform': AddressForm,
        'baform': AddressForm,
    }

    return render(request, 'services/personal_data.html', context)

def verification(request):
    if not request.user.is_authenticated():
        return redirect('/')

    if request.user.verified:
        return redirect('services:manage')

    return render(request, 'services/verification.html')

templates/services/category.html
{% extends 'skeleton.html' %}
{% block title %}{{ category }} - {% endblock %}

{% block content %}
    <h1 class="center">{{ category }} nahe {{ plz.plz }}, {{ plz.name }}</h1>
    <ol id="search-results">
    {% for service in servicelist %}
        <li>
        <a href="{% url 'services:service' service.1.pk %}">{{ service.1 }}</a>
        - {{ service.1.average_rating }} Sterne
        - {{ service.0 }} Km
        </li>
    {% endfor %}
    </ol>
    <br>
    <div id="pagination">
    {% if servicelist.has_previous %}
        <a href="?plz={{ plz.plz }}&p={{ servicelist.previous_page_number }}">Zurück</a>
    {% endif %}
    <span class="current">
        Seite {{ servicelist.number }} von {{ servicelist.paginator.num_pages }}
    </span>
    {% if servicelist.has_next %}
        <a href="?plz={{ plz.plz }}&p={{ servicelist.next_page_number }}">Vor</a>
    {% endif %}
    </div>
{% endblock %}

templates/services/manage.html
{% extends 'skeleton.html' %}
{% block title %}Benutzer - {% endblock %}

{% block content %}
<!-- inline styles => stylesheet -->
<div style="overflow: hidden">
<div style="float: left; width: 70%">
    <div style="float: left; text-align: center; width: 50%">
        <div style="font-size: 5em; line-height: 1em">
            {{ user.paid }}
        </div>
        Tage bezahlt
        <br />
        <a href="{% url 'payments:payment' %}">Jetzt mehr Tage kaufen</a>
        {% if not user.subscribed %}
            <br />
            <a href="{% url 'payments:subscription' %}">Upgraden auf jährliche Zahlung</a>
        {% endif %}
    </div>

    <div style="float: left; text-align: center; width: 50%">
        <div style="font-size: 5em; line-height: 1em">
            {{ user.num_services }}
        </div>
        Anzeigen aktiv
    </div>

    <div style="clear: both">
        <h3>Services</h3>
        {% for lst in listings %}
            <div>
                <h4>{{ lst.name }}</h4>
                <li>Branche: {{ lst.category }}</li>
                <li>Bewertungen: <a href="">{{ lst.num_ratings }} ({{ lst.average_rating }}&#x2605)</a></li>
            </div>
        {% empty %}
            Sie bieten im Moment keine Services an.
        {% endfor %}
    </div>
</div>

<!-- list-style: none -->
<div style="float: right; width: 30%">
    <div>
        <h4>Anzeigenverwaltung</h4>
        <li><a href="{% url 'payments:list' %}">Zahlungen verwalten</a></li>
    </div>

    <div>
        <h4>Accountverwaltung</h4>
        {% if not user.verified %}
            <li><a href="{% url 'services:verification' %}" style="font-weight: bold">Account verifizieren</a></li>
        {% endif %}
        <li><a href="{% url 'services:personal_data' %}">Persönliche Daten verwalten</a></li>
        <li><a href="{% url 'auth_password_change' %}">Passwort ändern</a></li>
    </div>
</div>
</div>
{% endblock %}

templates/services/payment.html
{% extends 'skeleton.html' %}

{% block content %}
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<form id="checkout" method="post" action="{% url 'renderer:checkout' %}">
    {% csrf_token %}
    <div id="dropin"></div>
    <input type="submit" value="Pay $10">
</form>
<script>
braintree.setup("{{ token }}", 'dropin', { container: 'dropin' });
</script>
{% endblock %}

templates/services/personal_data.html
{% extends 'skeleton.html' %}

{% block title %}Persönliche Daten - {% endblock %}

{% block content %}
<div style="text-align: center">
    <form action="." method="POST">
        <h4>Persönliche Daten</h4>
        <table style="margin: auto; width: 600px">
        {{ pdform.as_table }}
        </table>

        <h4>Rechnungsadresse</h4>
        <table style="margin: auto; width: 600px">
        {{ paform.as_table }}
        </table>

        <h4>Rechnungsadresse</h4>
        <table style="margin: auto; width: 600px">
        {{ baform.as_table }}
        </table>

        {% csrf_token %}
        <input type="Submit" />
    </form>
</div>
{% endblock %}

templates/services/search.html
{% extends 'skeleton.html' %}

{% block title %}Suche nach {{ category }} - {% endblock %}

{% block content %}
    <h1 class="center">Suche nach {{ category }}</h1>
    <div class="center">
    <form action="{% url 'services:category' category.pk %}" method="GET">
        <input type="text" name="plz" placeholder="Postleitzahl">
        <input type="submit" name="submit" value="Suchen">
    </form>
    </div>
{% endblock %}

templates/services/service.html
{% extends 'skeleton.html' %}

{% block title %}{{ service }} - {% endblock %}

{% block content %}
    <h1 class="center">{{ service }}</h1>
    <div class="indent">
        <p>
            {{ service.desc }}
        </p>
        <a href="{{ service.website }}" target="new">Unsere Website</a>
    </div>
    {% if contact == 0 %}
    <form action="." method="POST">
        {% csrf_token %}
        {#{{ form }} #}
        <input type="submit" />
    </form>
    {% else %}
        <h3 class="indent">Kontakt:</h3>
        <p class="indent">Telefon: {{ service.tel }}</p>
    {% endif %}
    {% if user.is_authenticated %}
        <p>
        <form action="" method="GET">
            Bewerten:
            <input type="radio" name="r" value="1"{% if rating.stars == 1 %} checked{% endif %}>1</option>
            <input type="radio" name="r" value="2"{% if rating.stars == 2 %} checked{% endif %}>2</option>
            <input type="radio" name="r" value="3"{% if rating.stars == 3 %} checked{% endif %}>3</option>
            <input type="radio" name="r" value="4"{% if rating.stars == 4 %} checked{% endif %}>4</option>
            <input type="radio" name="r" value="5"{% if rating.stars == 5 %} checked{% endif %}>5</option>
            Sterne
            <br>
            <textarea name="rt">{{ rating.text }}</textarea>
            <input type="submit">
        </form>
        </p>
    {% else %}
        <p>
        <a href="{% url 'auth_login' %}">Login / Registrieren</a>
        zum Bewerten.
        </p>
    {% endif %}
    {% if ratings %}
    <p>Durchschnittliche Bewertung: {{ service.average_rating }}</p>
    <h2>Bewertungen</h2>
        {% for rating in ratings %}
            <h3>{{ rating.by }}</h3>
            <span style="font-size: 85%">
                {{ rating.stars }} Sterne - {{ rating.at }}
            </span>
            {% if rating.text %}
                <p>{{ rating.text }}</p>
            {% endif %}
        {% endfor %}
        <br>
        {% if ratings.has_previous %}
            <a href="?&p={{ ratings.previous_page_number }}">Zurück</a>
        {% endif %}
        <span class="current">
            Seite {{ ratings.number }} von {{ ratings.paginator.num_pages }}
        </span>
        {% if ratings.has_next %}
            <a href="?&p={{ ratings.next_page_number }}">Vor</a>
        {% endif %}
    {% endif %}
{% endblock %}

templates/services/verification.html
{% extends 'skeleton.html' %}

{% block title %}Verifizierung - {% endblock %}

{% block content %}
{% endblock %}