notdienste/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html',
        'redirect_field_name': 'redirect'},
        name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'},
        name='logout'),
    url(r'^p/', include('payments.urls', namespace='payments')),
    url(r'', include('services.urls', namespace='services')),
)

payments/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from payments import views

urlpatterns = patterns('payments.views',
    url(r'^l/$', 'list', name='list'),
    url(r'^b/(\d)$', 'bill', name='bill'),
    url(r'^p/$', 'payment', name='payment'),
    url(r'^co/$', 'checkout', name='checkout'),
    url(r'^s/$', 'subscription', name='subscription'),
)

payments/models.py
from django.db import models

from services.models import User

class Payment(models.Model):
    yearly = models.BooleanField(default=False)
    amount = models.IntegerField()
    date = models.DateField(auto_now=True)
    user = models.ForeignKey(User)

    def __str__(self):
        return 'Payment {}: {}€ on {} by {}'.format(self.pk, self.amount,
            self.date, self.user)

    def pretty(self):
        return 'Zahlung über {}€ am {}'.format(self.amount, self.date)

payments/views.py
from django.shortcuts import render, redirect, get_object_or_404

from notdienste.settings import PAYMENT_BACKEND, MONTHLY_PRIZE
from payments.models import Payment
from payments.util import create_payment
from services.models import User

def list(request):
    if not request.user.is_authenticated():
        return redirect('/')

    payments = Payment.objects.filter(user=request.user).order_by('-date')

    context = {
        'payments': payments,
    }

    return render(request, 'payments/list.html', context)

def bill(request, pid):
    if not request.user.is_authenticated():
        return redirect('/')

    payment = get_object_or_404(Payment, pk=pid)

    # TODO Generate a bill to print out.

    return render(request, 'services/bill.html')

def payment(request):
    if not request.user.is_authenticated():
        return redirect('/')

    context = {
        'token': PAYMENT_BACKEND.get_client_token(request.user),
    }

    return render(request, 'payments/payment.html', context)

def checkout(request):
    if request.method != 'POST' or not request.user.is_authenticated():
        return redirect('/')

    if create_payment(request.user, request.POST.get('payment_method_nonce'),
        MONTHLY_PRIZE):
        p = Payment()
        p.yearly = False # This is a monthly payment.
        p.user = request.user
        p.amount = MONTHLY_PRIZE
        p.save()

        request.user.paid += 30
        request.user.save()

        return render(request, 'payments/payment_complete.html')
    else:
        return render(request, 'payments/payment_failed.html')

def subscription(request):
    if not request.user.is_authenticated():
        return redirect('/')

    if request.method == 'POST':
        if request.POST.get('sub')  and not request.user.subscribed:
            request.user.subscribed = True
            request.user.save()
            # TODO generate a bill and send it
            # TODO indicate success
        elif request.POST.get('unsub') and request.user.subscribed:
            request.user.subscribed = False
            request.user.save()
            # TODO indicate success

    return render(request, 'payments/subscription.html')

templates/payments/list.html
{% extends 'skeleton.html' %}
{% block title %}Zahlungen - {% endblock %}

{% block content %}
{% for p in payments %}
    <div>
    {{ p.pretty }} <a href="{% url 'payments:bill' p.pk %}">Rechnung ausdrucken</a>
    </div>
{% empty %}
    Sie haben noch keine Zahlungen getätigt.
{% endfor %}
{% endblock %}

templates/payments/payment.html
{% extends 'skeleton.html' %}

{% block content %}
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<form id="checkout" method="post" action="{% url 'payments:checkout' %}">
    {% csrf_token %}
    <div id="dropin"></div>
    <input type="submit" />
</form>
<script>
braintree.setup("{{ token }}", 'dropin', { container: 'dropin' });
</script>
{% endblock %}

templates/payments/payment_complete.html
{% extends 'skeleton.html' %}

{% block title %}Bezahlen - {% endblock %}

{% block content %}
<h4>Erfolg!</h4>
<p>Der Bezahlvorgang wurde erfolgreich abgeschlossen.</p>
{% endblock %}

templates/payments/payment_failed.html
{% extends 'skeleton.html' %}

{% block title %}Fehler - {% endblock %}

{% block content %}
<h4>Fehler!</h4>
<p>Der Bezahlvorgang wurde nicht erfolgreich abgeschlossen. Falls dieses
Problem bestehen bleibt, kontaktieren Sie bitte den Support.</p>
{% endblock %}

templates/payments/subscription.html
{% extends 'skeleton.html' %}

{% block title %}Jährliche Zahlung - {% endblock %}

{% block content %}

{% if user.subscribed %}
    [[ User is subscribed. ]]

    <br />

    <form action="." method="POST">
        {% csrf_token %}
        <input type="checkbox" name="unsub" />
        Ich will mein bestehendes Abonnement kündigen.
        <br />
        <input type="submit" />
    </form>
{% else %}
    [[ User is not subscribed. ]]

    <br />

    TODO: Add some info about the subscription.

    <form action="." method="POST">
        {% csrf_token %}
        <input type="checkbox" name="sub" />
        Ich will ein Abonnement abschließen.
        <br />
        <input type="submit" />
    </form>
{% endif %}

{% endblock %}