notdienste/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html',
        'redirect_field_name': 'redirect'},
        name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'},
        name='logout'),
    url(r'^p/', include('payments.urls', namespace='payments')),
    url(r'', include('services.urls', namespace='services')),
)

payments/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from payments import views

urlpatterns = patterns('payments.views',
    url(r'^l/$', 'list', name='list'),
    url(r'^b/(\d)$', 'bill', name='bill'),
    url(r'^p/$', 'payment', name='payment'),
    url(r'^co/$', 'checkout', name='checkout'),
    url(r'^s/$', 'subscription', name='subscription'),
)

renderer/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from renderer import views

urlpatterns = patterns('renderer.views',
    url(r'^$', 'index', name='index'),
    url(r'^e/(\d)/$', 'search', name='search'),
    url(r'^c/(\d)/$', 'category', name='category'),
    url(r'^s/(\d)/$', 'service', name='service'),
    url(r'^m/$', 'manage', name='manage'),
    url(r'^p/$', 'payment', name='payment'),
    url(r'^co/$', 'checkout', name='checkout'),
)

templates/error.html
{% extends 'skeleton.html' %}

{% block title %}Fehler - {% endblock %}

{% block content %}
    <h1 class="center">Fehler</h1>
    <p class="indent">
        {{ error }}
    </p>
{% endblock %}

templates/index.html
{% extends 'skeleton.html' %}

{% block title %}{% endblock %}

{% block content %}
    <h1 class="center">Welche Art Dienst ben&ouml;tigen Sie?</h1>
    <ul id="intro">
    {% for category in categories %}
        <li>
        <a href="{% url 'services:search' category.pk %}">{{ category }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/skeleton.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'nd-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'nd-responsive.css' %}">
    <title>{% block title %}{% endblock %}Notdienste</title>
</head>
<body>
<div id="wrapper">
    <header id="header">
        <!-- MENUE -->
        <div id="div-menue">
            <ul id="menue" class="ul-menue">
                <li>
                    <a href="{% url 'services:index' %}">Suchen</a>
                </li>
                <li>
                    <a href="business">Gewerbetreibende</a>
                </li>
                <li>
                    <a href="{% url 'services:manage' %}">Benutzer</a>
                </li>
                <li>
                    <a href="impressum">Impressum</a>
                </li>
                <li>
                    <a href="contact">Kontakt</a>
                </li>
            </ul>
            <div style="clear:left;"></div>
        </div>
    </header>
    <div id="content">
        <div id="user">
            {% if user.is_authenticated %}
                Wilkommen zurück,
                {% if user.first_name %}
                    {{ user.first_name }}
                {% else %}
                    {{ user.username }}
                {% endif %}
                    | <a href="{% url 'auth_logout' %}">Logout</a>
                {% else %}
                    Willkommen Gast
                    | <a href="{% url 'auth_login' %}">Login / Registrieren</a>
            {% endif %}
        </div>
        {% block content %}
            Wenn dies sichtbar ist, fehlt der Content-Block.
        {% endblock %}
    </div>
    <footer id="footer">
        <!-- FOOTER CONTENT -->
        <div id="foot-cont">
            Notdienste &copy; 2014 | Impressum
        </div>
    </footer>
</div>
</body>
</html>